{% set version = "3.100" %}

package:
  name: lame
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/sourceforge/lame/lame-{{ version }}.tar.gz
  sha256: ddfe36cab873794038ae2c1210557ad34857a4b6bdc515785d1da9e175b1da1e
  patches:
    - libmp3lame.patch
    - fixup_windows_build.patch

build:
  number: 1002
  run_exports:
    # seems to be minor version compatibility
    # https://abi-laboratory.pro/tracker/timeline/lame/
    - {{ pin_subpackage('lame', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make  # [unix]
    - nasm  # [win]

test:
  commands:
    - lame --genre-list testcase.mp3
    - lame --longhelp

about:
  home: https://lame.sourceforge.io/
  license: LGPL
  license_file: LICENSE
  summary: 'High quality MPEG Audio Layer III (MP3) encoder'

  # The remaining entries in this section are optional, but recommended
  description: |
    LAME is a high quality MPEG Audio Layer III (MP3) encoder licensed under the LGPL.
    Today, LAME is considered the best MP3 encoder at mid-high bitrates and at VBR, mostly
    thanks to the dedicated work of its developers and the open source licensing model
    that allowed the project to tap into engineering resources from all around the world.
  doc_url: http://lame.sourceforge.net/using.php
  dev_url: https://svn.code.sf.net/p/lame/svn/trunk/lame/

extra:
  recipe-maintainers:
    - soumith
    - hmaarrfk
